# .github/workflows/ci.yml
name: CI Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9, 3.10, 3.11]
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine
    
    - name: Build package
      run: |
        python -m build
    
    - name: Build Docker images
      run: |
        docker build -f docker/Dockerfile -t aaml-framework:${{ github.ref_name }} .
        docker build -f docker/Dockerfile.auditor -t aaml-auditor:${{ github.ref_name }} .
        docker build -f docker/Dockerfile.trainer -t aaml-trainer:${{ github.ref_name }} .
        docker build -f docker/Dockerfile.federated -t aaml-federated:${{ github.ref_name }} .
    
    - name: Push to Docker Hub
      env:
        DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
      run: |
        echo $DOCKER_HUB_TOKEN | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin
        docker push aaml-framework:${{ github.ref_name }}
        docker push aaml-auditor:${{ github.ref_name }}
        docker push aaml-trainer:${{ github.ref_name }}
        docker push aaml-federated:${{ github.ref_name }}
    
    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |
          See [CHANGELOG.md](https://github.com/${{ github.repository }}/blob/main/CHANGELOG.md) for details.
        draft: false
        prerelease: false

